spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db
    username: bestuser
    password: bestuser

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: update
          import_files: init.sql
          charset_name: UTF-8

  mvc:
    hidden-method:
      filter:
        enabled: true

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
